### ISSUE TITLE
Not working on Jupyter 4.3

### ISSUE THREAD

**Issue by aiguofer** [jupyter-incubator/dashboards#281]
Haven't had time to dig much into it, but it looks like call to `/api/kernels` is getting a 403, possibly due to the security changes that they made. Btw, my notebook is running with 
```
c.NotebookApp.token = ''
c.NotebookApp.password = ''
```

here's what I see in console:
```
dashboard.js:108 Error: Failed to create kernel: API request failed (403): Forbidden
    at kernel.js:65
```

**Comment by parente** [comment]
Is this just using the dashboard layout extension? Or deploying it as a local dashboard?

**Comment by parente** [comment]
I conda installed notebook 4.3.1 and jupyter_dashboards 0.6.1. I fired up `jupyter notebook` without any options and was able to drag/drop my cells into a layout without any problems. 

I went back and ran with `jupyter notebook --NotebookApp.token='' --NotebookApp.password=''` and everything worked fine too.

**Comment by aiguofer** [comment]
Hey, sorry this is actually with the dashboard server, I accidentally created it against the wrong project.

**Comment by aiguofer** [comment]
created over there https://github.com/jupyter-incubator/dashboards_server/issues/311

**Comment by parente** [comment]
Not a problem. Thanks for reporting it regardless!
